kinsu-objs := core/init.o

kinsu-objs += feature/kernel_umount.o
kinsu-objs += feature/sulog.o
kinsu-objs += feature/sucompat.o

kinsu-objs += hook/lsm_hook.o
kinsu-objs += hook/setuid_hook.o
kinsu-objs += hook/syscall_event_bridge.o
kinsu-objs += hook/syscall_hook_manager.o
kinsu-objs += hook/tp_marker.o
ifeq ($(CONFIG_ARM64),y)
kinsu-objs += hook/arm64/patch_memory.o
kinsu-objs += hook/arm64/syscall_hook.o
else ifeq ($(CONFIG_X86_64),y)
kinsu-objs += hook/x86_64/patch_memory.o
kinsu-objs += hook/x86_64/syscall_hook.o
endif

kinsu-objs += infra/file_wrapper.o
kinsu-objs += infra/event_queue.o
kinsu-objs += infra/seccomp_cache.o
kinsu-objs += infra/su_mount_ns.o
kinsu-objs += infra/symbol_resolver.o

ifneq ($(CONFIG_KSU_DISABLE_MANAGER),y)
kinsu-objs += manager/apk_sign.o
kinsu-objs += manager/pkg_observer.o
kinsu-objs += manager/throne_tracker.o
endif

kinsu-objs += policy/allowlist.o
kinsu-objs += policy/app_profile.o
kinsu-objs += policy/feature.o

kinsu-objs += runtime/boot_event.o
kinsu-objs += runtime/ksud_integration.o

kinsu-objs += selinux/selinux.o
kinsu-objs += selinux/rules.o
kinsu-objs += selinux/sepolicy.o

kinsu-objs += sulog/event.o
kinsu-objs += sulog/fd.o

kinsu-objs += supercall/dispatch.o
kinsu-objs += supercall/perm.o
kinsu-objs += supercall/supercall.o

kinsu-objs += feature/adb_root.o

kinsu-objs += feature/selinux_hide.o

# These objects must be linked into vmlinux. KernelPatch installs the
# sukisu_kpm_* hooks during early boot, before loadable modules exist.
obj-$(CONFIG_KPM) += kpm/compact.o
obj-$(CONFIG_KPM) += kpm/kpm.o
obj-$(CONFIG_KPM) += kpm/super_access.o

# SUSFS support - compile susfs sources when enabled
ifdef KSU_SUSFS
ccflags-y += -DCONFIG_KSU_SUSFS=1
kinsu-objs += susfs/susfs.o
kinsu-objs += susfs/susfs_coredump.o
kinsu-objs += susfs/sucompat.o
$(info -- KernelSU SUSFS: enabled)
endif

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_KSU_DISABLE_MANAGER),y)
ccflags-y += -DCONFIG_KSU_DISABLE_MANAGER=1
endif
ifeq ($(CONFIG_KSU_DISABLE_POLICY),y)
ccflags-y += -DCONFIG_KSU_DISABLE_POLICY=1
endif
ifeq ($(CONFIG_KSU_DEBUG),y)
ccflags-y += -DCONFIG_KSU_DEBUG=1
endif
endif

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifeq ($(filter /%,$(src)),)
KSU_KERNEL_DIR := $(srctree)/$(src)
else
KSU_KERNEL_DIR := $(src)
endif

ccflags-y += -I$(KSU_KERNEL_DIR) -I$(KSU_KERNEL_DIR)/include

obj-$(CONFIG_KSU) += kinsu.o

MDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Workaround bazel
# https://github.com/tiann/KernelSU/pull/316#issuecomment-1479043219
GIT := $(shell PATH="$$PATH":/usr/bin:/usr/local/bin which git)
ifneq ($(GIT),)
# Check if this is a git repository
# Try to detect Git repo intelligently
GIT_ROOT := $(shell cd $(MDIR) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),)
KERNEL_GIT_ROOT := $(shell cd $(srctree) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),$(KERNEL_GIT_ROOT))
# Only set version if it's a different repo from kernel
$(shell cd $(GIT_ROOT) && [ -f .git/shallow ] && $(GIT) fetch --unshallow 2>/dev/null || true)
KSU_GIT_VERSION := $(shell cd $(GIT_ROOT) && $(GIT) rev-list --count HEAD 2>/dev/null)
ifneq ($(strip $(KSU_GIT_VERSION)),)
KSU_GIT_VERSION_VALID := 1
endif
$(info -- KernelSU: Git repo detected at $(GIT_ROOT))
endif
endif
else
$(warning -- KernelSU: Git not detected, make sure git is installed in your PATH!)
endif


# Calculate version if git version is available
ifdef KSU_GIT_VERSION_VALID
# ksu_version: 30000 + git revision count, matching the manager's 3.x ABI.
$(eval KSU_VERSION=$(shell v=$$(expr 30000 + $(KSU_GIT_VERSION)); \
	[ $$v -lt 32513 ] && echo 32513 || echo $$v))
$(info -- KernelSU version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
else
# If there is no .git directory, use default version
$(warning "KSU_GIT_VERSION not defined! It is better to make KernelSU a git repository!")
ccflags-y += -DKSU_VERSION=32513
endif

KSU_NEW_DCACHE_FLUSH := $(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h ; echo $$?)
$(info -- KSU_NEW_DCACHE_FLUSH: $(KSU_NEW_DCACHE_FLUSH))


ifndef KSU_EXPECTED_SIZE
KSU_EXPECTED_SIZE := 0x2d4
endif

ifndef KSU_EXPECTED_HASH
KSU_EXPECTED_HASH := eb4ae49882e0ea80c13989ea2141368b1f819e2bfe10801b3c15b743bd647dab
endif

ifndef KSU_MANAGER_PACKAGE
KSU_MANAGER_PACKAGE := com.mikokernel
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
$(info -- KernelSU Manager package name: $(KSU_MANAGER_PACKAGE))
endif

$(info -- KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
$(info -- KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))

ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"

ifdef KSU_EXPECTED_SIZE2
ifndef KSU_EXPECTED_HASH2
$(error KSU_EXPECTED_HASH2 must be set when KSU_EXPECTED_SIZE2 is set)
endif
ccflags-y += -DEXPECTED_SIZE2=$(KSU_EXPECTED_SIZE2)
ccflags-y += -DEXPECTED_HASH2=\"$(KSU_EXPECTED_HASH2)\"
$(info -- KernelSU Manager signature size2: $(KSU_EXPECTED_SIZE2))
$(info -- KernelSU Manager signature hash2: $(KSU_EXPECTED_HASH2))
endif

ccflags-y += -DKSU_NEW_DCACHE_FLUSH=$(KSU_NEW_DCACHE_FLUSH)

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function

# Keep a new line here!! Because someone may append config
