#!/usr/bin/env python3
"""
Extract APK v2 signature information for KernelSU manager recognition.
Generates EXPECTED_SIZE and EXPECTED_HASH for kernel compilation.
"""

import sys
import struct
import hashlib
from pathlib import Path
from typing import Optional, Tuple

def find_signing_block(apk_path: Path) -> Optional[Tuple[int, int]]:
    """Find APK Signing Block v2 offset and size."""
    with open(apk_path, 'rb') as f:
        # Find EOCD (End of Central Directory)
        f.seek(-22, 2)  # Minimum EOCD size
        file_size = f.tell() + 22

        # Search for EOCD signature
        for i in range(0xffff):
            f.seek(-22 - i, 2)
            if f.read(4) == b'PK\x05\x06':
                break
        else:
            print("Error: Cannot find EOCD")
            return None

        # Read central directory offset
        f.seek(-22 - i + 16, 2)
        cd_offset = struct.unpack('<I', f.read(4))[0]

        # Check for APK Signing Block
        f.seek(cd_offset - 16)
        magic = f.read(16)
        if magic != b'APK Sig Block 42':
            print("Error: No APK Signing Block v2 found")
            return None

        # Read block size
        f.seek(cd_offset - 24)
        block_size = struct.unpack('<Q', f.read(8))[0]

        block_offset = cd_offset - block_size - 8

        return block_offset, block_size

def extract_v2_certificate(apk_path: Path) -> Optional[Tuple[int, str]]:
    """Extract v2 signing certificate size and SHA256 hash."""
    result = find_signing_block(apk_path)
    if not result:
        return None

    block_offset, block_size = result

    with open(apk_path, 'rb') as f:
        f.seek(block_offset + 8)  # Skip size field

        # Parse signing block sequences
        remaining = block_size - 8
        while remaining > 12:
            seq_len = struct.unpack('<Q', f.read(8))[0]
            if seq_len == block_size:
                break

            sig_id = struct.unpack('<I', f.read(4))[0]
            remaining -= 12

            # 0x7109871a = APK Signature Scheme v2
            if sig_id == 0x7109871a:
                # Read signer sequence
                f.read(4)  # signer-sequence length
                f.read(4)  # signer length
                f.read(4)  # signed data length

                # Read digests
                digests_len = struct.unpack('<I', f.read(4))[0]
                f.seek(digests_len, 1)  # Skip digests

                # Read certificates
                f.read(4)  # certificates length
                cert_len = struct.unpack('<I', f.read(4))[0]

                if cert_len > 0 and cert_len < 10240:  # Sanity check
                    cert_data = f.read(cert_len)
                    cert_hash = hashlib.sha256(cert_data).hexdigest()
                    return cert_len, cert_hash
                else:
                    print(f"Warning: Invalid certificate size: {cert_len}")
                    return None
            else:
                # Skip this block
                f.seek(seq_len - 4, 1)
                remaining -= seq_len - 4

    print("Error: v2 signature not found in signing block")
    return None

def generate_kernel_header(cert_size: int, cert_hash: str, package_name: str, output_path: Path):
    """Generate kernel header file with manager identity."""
    header_content = f"""/* Auto-generated by extract_apk_signature.py - DO NOT EDIT */
#ifndef __KSU_H_MANAGER_IDENTITY_SIGNATURE
#define __KSU_H_MANAGER_IDENTITY_SIGNATURE

/* Manager package name */
#define KSU_MANAGER_PACKAGE "{package_name}"

/* APK v2 signature certificate size (bytes) */
#define EXPECTED_SIZE {cert_size}

/* APK v2 signature certificate SHA256 hash */
#define EXPECTED_HASH "{cert_hash}"

#endif /* __KSU_H_MANAGER_IDENTITY_SIGNATURE */
"""

    output_path.write_text(header_content, encoding='utf-8')
    print(f"✓ Generated: {output_path}")
    print(f"  Package: {package_name}")
    print(f"  Cert Size: {cert_size} bytes")
    print(f"  Cert Hash: {cert_hash}")

def main():
    if len(sys.argv) < 2:
        print("Usage: extract_apk_signature.py <apk_file> [output_header]")
        print("\nExtracts APK v2 signature for KernelSU manager recognition.")
        sys.exit(1)

    apk_path = Path(sys.argv[1])
    if not apk_path.exists():
        print(f"Error: APK file not found: {apk_path}")
        sys.exit(1)

    print(f"Analyzing APK: {apk_path}")

    result = extract_v2_certificate(apk_path)
    if not result:
        print("Failed to extract signature information")
        sys.exit(1)

    cert_size, cert_hash = result

    # Default output path
    if len(sys.argv) >= 3:
        output_path = Path(sys.argv[2])
    else:
        output_path = Path(__file__).parent.parent / "KernelSU" / "kernel" / "manager" / "manager_signature.h"

    # Package name from build.gradle.kts
    package_name = "com.mikokernel"

    generate_kernel_header(cert_size, cert_hash, package_name, output_path)

    print("\n✓ Signature extraction completed successfully!")
    print(f"\nNext steps:")
    print(f"1. Include this header in kernel/manager/apk_sign.c")
    print(f"2. Rebuild kernel module with updated signature")
    print(f"3. Flash the patched boot image")

if __name__ == "__main__":
    main()
